#!/bin/bash

echo "+     +8     +16     +24     +32     +40     +48     +56     +64     +72     +80" |\

/bin/lemonbar -bdp \
		-g 1120x32+720+1296 \
		-n "bar" \
		-f "Roboto Mono:size=9" \
		-B "#ffffea" \
		-F "#111111"

sleep 2

raisebar
