#!/usr/bin/bash

clock() {
	DATE=$(date "+%Y.%m.%d")
	TIME=$(date "+%H:%M")
	echo -n "${DATE}"
}

battery() {
	BATPERC="$(< /sys/class/power_supply/BAT0/capacity)"
	echo -en "\uf0e7 $BATPERC%"
}

heat() {
	CELCIUS=$(sensors | grep "Core 1" | cut -c 17-23 | sed 's/\.[[:digit:]]//')
	echo -en "\uf2c9  $CELCIUS"
}

brightness() {
	cur="$(< /sys/class/backlight/intel_backlight/brightness)"
	max="$(< /sys/class/backlight/intel_backlight/max_brightness)"
	perc="$((cur * 100 / $max))%"
	echo -en "\uf185  $perc"
}

volume() {
	VOL="$(amixer get Master | tail -n 1 | cut -d '[' -f 2 | sed 's/].*//g')"
	echo -en "\uf026  $VOL"
}

while true; do
	echo "%{l}%{O31}$(clock)"
#	      %{c}%{O32}$(volume)\
#	      %{r}$(heat)%{O24}$(battery)%{O31}"
	sleep 2
done |\



/bin/lemonbar -bd \
		-g 1060x80+750+437 \
		-f "Roboto:size=9" \
		-f "Source Han Sans JP:size=9" \
		-f "Font Awesome 5 Free:size=10:style=Solid" \
		-o -4 \
		-o -3 \
		-o -5 \
		-n "bar" \
		-B\#faebd7 \
		-F\#1e2d1c
