#!/usr/bin/bash

clock() {
	DATE=$(LC_ALL=ja_JP.UTF-8 date | cut -c10-23 | sed 's/  / /g')
	TIME=$(date "+%H:%M")
	echo -n "${DATE} - ${TIME}"
}


while true; do
	echo "%{c}$(clock)"
	sleep 60
done |\

    
/bin/lemonbar -bd \
		-g 132x32+894+24 \
		-f "Roboto:size=11" \
		-f "Noto Sans CJK JP:size=11" \
		-o -2 \
		-o -1 \
		-n "bar" \
		-B\#e8e8e8 \
		-F\#1e2d1c
