#!/bin/bash
# rofi_system_dmenu.sh / JennyM 2017 malkalech.com

list=(
  "ウェブ" "chromium"
  "ファイル" "st -e ranger"
  "カラー" "gpick"
  "デザイン" "figma"
  "画像編集" "gimp"
  "再起動" "systemctl reboot"
  "システム終了" "systemctl poweroff"
  "qutebrowser" "qutebrowser"
)

if selected="$(for (( i=0; i<=$((${#list[@]}/2-1)); i++ )) { echo "${list[($i+1)*2-2]}"; } | rofi -dmenu -i -format i)"; then
  [[ "$selected" -ge 0 ]] && eval "${list[($selected+1)*2-1]}"
fi
