#!/bin/sh


DMENU='dmenu -w 400 -x 760 -y 420 -nb #f0ecdc -nf #1e2d1c -sb #1e2d1c -sf #f0ecdc'

choice=$(echo -e "acme\nwww\nfile\nimg\nrboot\noff" | $DMENU)

case "$choice" in
	acme) x ;;
	www) firefox ;;
	file) st -g 17x16 -e noice ~/ ;;
	img) sxiv -t ~/img ;;
	rboot) sudo reboot ;;
	off) sudo poweroff ;;
esac
