#!/bin/sh


DMENU='dmenu -w 200 -x 860 -y 420'

choice=$(echo -e "write\nwww\nfile\nimg\nrboot\noff" | $DMENU)

case "$choice" in
	write) rxvt -g 80x40 -e skkfep ;;
	www) firefox ;;
	file) rxvt -name files -fn 6x13 -g 80x16+910+434 -e noice ~/ ;;
	img) sxiv -tb ~/img ;;
	rboot) sudo reboot ;;
	off) sudo poweroff ;;
esac
