#!/usr/bin/bash
#
# Description: Blur and lock the screen
# Dependencies: imagemagick and i3lock

sleep 0.1

tmp="/tmp/screen.png"
tmp2="/tmp/lock.png"
tmp3="/tmp/bg.png"
lock="${HOME}/.bin/lock.png"
colr="${HOME}/.colors"

letters=16
fontHeight=16
fontWidth=11
padding=140
height=$(( $fontHeight + $padding ))
width=$(( ( ( $fontWidth * $letters ) - 1 ) + $padding )) 

wht=`cat $colr | grep "wht" | awk '{ print $3 }'`
blk=`cat $colr | grep "blk" | awk '{ print $3 }'`
red=`cat $colr | grep "red" | awk '{ print $3 }'`

# Take a screenshot
import -window root "$tmp"

# Blur it
convert "$tmp" -scale 5% -scale 2000% "$tmp"
convert "$tmp" -fill "$blk" -colorize 50% "$tmp"

convert "$lock" "$tmp2"

# Create label's background
convert -size ${width}x${height} xc:#000000 "$tmp3"

# Merge
convert "$tmp3" "$tmp2" -gravity center -composite "$tmp2"
convert "$tmp" "$tmp2" -gravity center -composite "$tmp"

# Lock the screen
i3lock -ue -i "$tmp"
