#!/bin/bash
# rofi_system_dmenu.sh / JennyM 2017 malkalech.com

list=(
  "インターネット" "firefox"
  "ファイル" "emacsclient -cn -F '((width . 37) (height . 30))' -e '(ranger)' x"
  "プレビュー" "thunar ~/壁紙/"
  "カラー" "st -e grabc"
  "デザイン" "inkscape"
  "画像編集" "gimp"
  "再起動" "sudo reboot"
  "システム終了" "sudo poweroff"
)

if selected="$(for (( i=0; i<=$((${#list[@]}/2-1)); i++ )) { echo "${list[($i+1)*2-2]}"; } | rofi -dmenu -i -format i)"; then
  [[ "$selected" -ge 0 ]] && eval "${list[($selected+1)*2-1]}"
fi
