#!/bin/bash
# rofi_system_dmenu.sh / JennyM 2017 malkalech.com

list=(
  "internet" "chromium"
  "file" "emacsclient -cn -F '((width . 28) (height . 24))' -e '(ranger)' x"
  "preview" "thunar ~/壁紙/"
  "color" "gpick"
  "design" "inkscape"
  "gimp" "gimp"
  "reboot" "sudo reboot"
  "shutdown" "sudo poweroff"
)

if selected="$(for (( i=0; i<=$((${#list[@]}/2-1)); i++ )) { echo "${list[($i+1)*2-2]}"; } | rofi -dmenu -i -format i)"; then
  [[ "$selected" -ge 0 ]] && eval "${list[($selected+1)*2-1]}"
fi
