#!/bin/sh
urxvtc -bg "#e0ddc8" -g 320x1+0+1063 -e mpv --msg-level=ao/netbsd=no,file=no,cplayer=no --term-status-msg='  ${filename} ${time-pos} (${percent-pos}%)' --shuffle --no-video --loop-playlist ~/av/audio/ &
